const id = Number(document.body.dataset.premise);
const items = {
  1:{title:'Una red no es solo conectar dispositivos',short:'Presentación de diseño de red.',type:'PDF · presentación',file:'media/network-design.pdf',kind:'pdf',accent:'#00ffcc',prev:'8 · Medios de transmisión',next:'2 · Internet y sociedad'},
  2:{title:'Internet: una solución tecnológica que transformó la sociedad',short:'Canción con letra para lectura manual · creada con IA.',type:'CANCIÓN · AUDIO',file:'premisa-2-cancion.html',kind:'song',accent:'#b44fff',prev:'1 · Diseño de red',next:'3 · Packet Tracer'},
  3:{title:'¿Qué pasaría si pudieras equivocarte sin consecuencias?',short:'Video de Packet Tracer.',type:'VIDEO · simulación',file:'https://github.com/Gangster-PC/portafolio-redes-internet/releases/download/v1.0.0/packet-tracer.mp4',kind:'video',accent:'#39ff14',prev:'2 · Internet y sociedad',next:'4 · La buena red'},
  4:{title:'Una red que funciona… ¿es necesariamente una buena red?',short:'Podcast técnico.',type:'VIDEO · podcast',file:'https://github.com/Gangster-PC/portafolio-redes-internet/releases/download/v1.0.0/good-network.mp4',kind:'video',accent:'#ff6b35',prev:'3 · Packet Tracer',next:'5 · Viaje del dato'},
  5:{title:'El viaje invisible de un dato',short:'Infografía del recorrido de la información.',type:'PDF · infografía',file:'media/data-journey.pdf',kind:'pdf',accent:'#ffd700',prev:'4 · La buena red',next:'6 · Internet como ciudad'},
  6:{title:'Si Internet fuera una ciudad, ¿cómo funcionaría?',short:'Historieta.',type:'IMAGEN · historieta',file:'media/internet-city.png',kind:'image',accent:'#ff2d78',prev:'5 · Viaje del dato',next:'7 · 24 horas sin Internet'},
  7:{title:'24 horas sin Internet… ¿qué tan dependientes somos?',short:'Periódico in English.',type:'IMAGEN · periódico',file:'media/without-internet.png',kind:'image',accent:'#ff1744',prev:'6 · Internet como ciudad',next:'8 · Por dónde viaja Internet'},
  8:{title:'¿Por dónde viaja Internet?',short:'Mapa conceptual.',type:'VIDEO · mapa conceptual',file:'media/transmission-media.mp4',kind:'video',accent:'#4fc3f7',prev:'7 · 24 horas sin Internet',next:'1 · Diseño de red'}
};
const p=items[id];
const learnings={
  1:[`Analizamos la evolución histórica de la conectividad, desde las primeras transmisiones en la red ARPANET hasta la consolidación del Modelo TCP/IP y el nacimiento de la World Wide Web.`,`Comprendimos la transición desde las redes conmutadas por circuitos hasta la conmutación por paquetes, identificando cómo este hito descentralizó la comunicación y garantizó la resiliencia en la transmisión de datos.`],
  2:[`Reflexionamos sobre la vulnerabilidad de las infraestructuras críticas modernas ante fallas sistemáticas en los protocolos de red y ataques cibernéticos a gran escala.`,`Examinamos el impacto ético, legal y social que representa la dependencia global de la conectividad digital y la centralización de datos en servidores en la nube.`],
  3:[`Desarrollamos habilidades prácticas en el diseño de topologías de red, asignación de direccionamiento IP estático, máscaras de subred y configuración de puertas de enlace (<em>Default Gateway</em>).`,`Validamos la conectividad de la red punto a punto mediante la ejecución de pruebas de diagnóstico con el protocolo ICMP (comando <code>ping</code>) y el análisis de la encapsulación en el modo simulación.`],
  4:[`Diferenciamos el Modelo OSI (estándar teórico de 7 capas) de la arquitectura TCP/IP (estándar práctico de 4 capas), comprendiendo por qué este último se consolidó como el estándar de mercado en Internet.`,`Analizamos la simplificación de capas superiores (Aplicación, Presentación y Sesión) en la pila TCP/IP y evaluamos la pertinencia de los protocolos TCP y UDP en la capa de transporte según el tipo de tráfico.`],
  5:[`Reconstruimos el flujo completo de información (ida y vuelta) a través de las 7 capas del Modelo OSI en el contexto de los videojuegos multijugador en tiempo real.`,`Identificamos la importancia del protocolo UDP en la capa de Transporte para minimizar la latencia y analizamos las consecuencias técnicas de una falla en la capa de Red (Capa 3) y Transporte (Capa 4).`],
  6:[`Estudiamos el funcionamiento interno y los puertos bien conocidos (<em>Well-Known Ports</em>) de protocolos fundamentales como HTTP/HTTPS, FTP, SMTP, SSH y DNS.`,`Comprendimos el proceso de establecimiento de conexión en tres vías (<em>Three-Way Handshake</em>) de TCP y cómo los protocolos de capa de aplicación garantizan la integridad o velocidad de la información.`],
  7:[`Diagnosticamos la arquitectura distribuida del Sistema de Nombres de Dominio (DNS) y su dependencia en los servidores raíz (<em>Root Servers</em>) y registros FQDN.`,`Evaluamos los procedimientos de mitigación técnica ante caídas globales (uso de <em>resolvers</em> alternativos como 8.8.8.8 / 1.1.1.1, edición de archivos <code>hosts</code>) y la implementación de Anycast y DNSSEC para prevenir ataques.`],
  8:[`Diseñamos un plan de infraestructura física de red para un entorno crítico (Hospital Digital), justificando la selección de medios guiados y no guiados.`,`Comparamos las características de transmisión de la Fibra Óptica (inmunidad a interferencias electromagnéticas) frente al Cobre UTP y redes inalámbricas Wi-Fi 6, estableciendo planes de contingencia por microondas/5G.`]
};
const learningSection=`<section class="learning-section" aria-labelledby="learning-title"><h2 id="learning-title">Aprendizajes</h2><ul>${learnings[id].map(item=>`<li>${item}</li>`).join('')}</ul></section>`;
const pageFor=n=>`premisa-${n}.html`;
const media=p.kind==='pdf'?`<iframe src="${p.file}" title="${p.short}"></iframe>`:p.kind==='video'?`<video controls preload="metadata" playsinline src="${p.file}"><p>Tu navegador no puede reproducir este producto. <a href="${p.file}">Abrir archivo</a>.</p></video>`:p.kind==='image'?`<button class="image-button" type="button"><img class="poster-image" src="${p.file}" alt="${p.short}" /></button>`:`<iframe src="${p.file}" title="${p.short}"></iframe>`;
document.title=`Premisa ${String(id).padStart(2,'0')} · ${p.title}`;
document.body.style.setProperty('--accent',p.accent);document.body.style.setProperty('--accent-glow',`${p.accent}33`);
document.body.innerHTML=`<main class="premise-shell"><header class="premise-topbar"><a class="hub-link" href="index.html">⌂ Hub</a><div class="topbar-center">Premisa ${String(id).padStart(2,'0')} · ${p.title}<small>${p.file.replace('media/','')}</small></div><a class="topbar-next" href="${pageFor(id===8?1:id+1)}">Premisa ${id===8?1:id+1} →</a></header><section class="premise-intro"><div class="intro-copy"><p class="eyebrow">PREMISA ${String(id).padStart(2,'0')} · ${p.type}</p><h1 class="premise-title">${p.title}</h1><p class="premise-short">${p.short}</p></div><div class="node-mark">${String(id).padStart(2,'0')}</div></section><section class="product-shell"><div class="product-toolbar"><span>PRODUCTO MULTIMODAL · ${p.type}</span><div class="toolbar-actions"><button class="toolbar-button" id="fullscreen" type="button">⛶ Pantalla completa</button><a class="toolbar-button" href="${p.file}" target="_blank" rel="noreferrer">↗ Abrir</a></div></div><div class="product-viewport ${p.kind==='image'?'image-product':''}">${media}</div><div class="product-caption"><span>${p.short}</span><a href="${p.file}" download>↓ Descargar</a></div></section>${learningSection}<nav class="premise-nav" aria-label="Cambiar de premisa"><a href="${pageFor(id===1?8:id-1)}"><span>← ANTERIOR</span><strong>${p.prev}</strong></a><a href="${pageFor(id===8?1:id+1)}"><span>SIGUIENTE →</span><strong>${p.next}</strong></a></nav><footer class="premise-footer"><span>Sleider Morales · Alejandro Triana · Andrés Salgado</span><a href="index.html">Volver al hub ↗</a></footer></main><div class="image-modal" hidden><button type="button" aria-label="Cerrar">×</button><img alt="" /></div>`;
document.querySelector('#fullscreen').addEventListener('click',()=>{const target=document.querySelector('.product-viewport');if(document.fullscreenElement)document.exitFullscreen();else target.requestFullscreen?.();});
const imgButton=document.querySelector('.image-button');if(imgButton){const modal=document.querySelector('.image-modal'),modalImg=modal.querySelector('img');imgButton.addEventListener('click',()=>{modalImg.src=p.file;modalImg.alt=p.short;modal.hidden=false;document.body.style.overflow='hidden';});modal.querySelector('button').addEventListener('click',()=>{modal.hidden=true;document.body.style.overflow='';});modal.addEventListener('click',e=>{if(e.target===modal){modal.hidden=true;document.body.style.overflow='';}});document.addEventListener('keydown',e=>{if(e.key==='Escape'){modal.hidden=true;document.body.style.overflow='';}});}
